[config]
default_to_workspace = false

[tasks.generate-parser]
cwd = "tree-sitter-dataflex"
condition = { files_modified = { input = ["grammar.js"], output = ["src/parser.c"] }}
script = "tree-sitter generate"

[tasks.sync-vscode-extension]
condition = { files_exist = [
    "${CARGO_MAKE_WORKING_DIRECTORY}/vscode-dataflex",
] }
run_task = { name = [
    "sync-vscode-extension-server",
] }

[tasks.sync-vscode-extension-server.windows]
script_runner = "@duckscript"
script = '''
    cp ${TARGET_PATH}/dataflex-lsp.exe vscode-dataflex/server/dataflex-lsp.exe
    cp ${TARGET_PATH}/dataflex_lsp.pdb vscode-dataflex/server/dataflex_lsp.pdb
'''

[tasks.sync-vscode-extension-server.mac]
script_runner = "@duckscript"
script = "cp ${TARGET_PATH}/dataflex-lsp vscode-dataflex/server/dataflex-lsp"

[tasks.sync-zed-extension]
condition = { files_exist = ["${CARGO_MAKE_WORKING_DIRECTORY}/zed-dataflex"] }
run_task = { name = [
    "sync-zed-extension-parser",
    "sync-zed-extension-highlights",
] }

[tasks.sync-zed-extension-parser]
command = "rsync"
args = [
    "-a",
    "--exclude",
    ".git",
    "tree-sitter-dataflex/",
    "zed-dataflex/grammars/dataflex",
]

[tasks.sync-zed-extension-highlights]
command = "rsync"
args = [
    "tree-sitter-dataflex/queries/highlights.scm",
    "zed-dataflex/languages/dataflex/highlights.scm",
]

[tasks.compile-vscode-extension]
cwd = "vscode-dataflex"
condition = { files_modified = { input = ["src/*"], output = ["out/extension.js", "out/extension.map"] }}
script = "npm run compile"

[tasks.create-vsix]
cwd = "vscode-dataflex"
script = "vsce package --target win32-x64"

[tasks.test-parser]
cwd = "tree-sitter-dataflex"
script = "tree-sitter test"

[tasks.test-dataflex-lsp]
cwd = "dataflex-lsp"
command = "cargo"
args = ["test"]

[tasks.debug]
env = { TARGET_PATH = "target/debug" }
run_task = { name = [
    "generate-parser",
    "build",
    "sync-vscode-extension",
    "sync-zed-extension",
    "compile-vscode-extension",
]}

[tasks.release]
env = { TARGET_PATH = "target/release" }
run_task = { name = [
    "generate-parser",
    "build-release",
    "sync-vscode-extension",
    "sync-zed-extension",
    "create-vsix",
]}

[tasks.test]
clear = true
run_task = { name = [
    "generate-parser",
    "test-parser",
    "test-dataflex-lsp",
]}

[tasks.default]
alias = "debug"
